MODEL:
  TYPE: bisenetv2
  BACKBONE: None
  NUM_CLASS: 4
  RESUME: None

LOSS: 
  TYPE: MainAuxLoss
  AUX_WEIGHT: [0.1, 0.2, 0.3, 0.4]
  META_LOSS_TYPE: "entropy"

DATA:
  DATASET: shelves
  INPUT_HEIGHT: 640
  INPUT_WIDTH: 640